"""empty message

Revision ID: 0f0efd275309
Revises: 0936d0f53506
Create Date: 2020-12-05 12:19:03.308751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f0efd275309'
down_revision = '0936d0f53506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.add_column('contracts', sa.Column('entry_price', sa.Float(), nullable=True))
    op.add_column('contracts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contracts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'user_id')
    op.drop_column('contracts', 'entry_price')
    op.drop_table('users')
    # ### end Alembic commands ###
